export const customersData = [
  {
    id: 11232,
    name: "Iqram Ashq",
    joinedDate: "Jun 29,2022",
    orderedItems: 1,
    status: "Block",
  },
  {
    id: 22345,
    name: "Sarah Johnson",
    joinedDate: "Jan 15, 2023",
    orderedItems: 3,
    status: "Active",
  },
  {
    id: 33456,
    name: "Michael Smith",
    joinedDate: "Mar 10, 2022",
    orderedItems: 5,
    status: "Active",
  },
  {
    id: 44567,
    name: "Emily Brown",
    joinedDate: "Apr 5, 2023",
    orderedItems: 2,
    status: "Active",
  },
  {
    id: 55678,
    name: "David Martinez",
    joinedDate: "Jul 21, 2022",
    orderedItems: 4,
    status: "Block",
  },
  {
    id: 66789,
    name: "Sophia Garcia",
    joinedDate: "Sep 8, 2023",
    orderedItems: 2,
    status: "Active",
  },
  {
    id: 77890,
    name: "Daniel Johnson",
    joinedDate: "Dec 3, 2022",
    orderedItems: 3,
    status: "Block",
  },
  {
    id: 88901,
    name: "Olivia Wilson",
    joinedDate: "Feb 14, 2023",
    orderedItems: 1,
    status: "Active",
  },
  {
    id: 99012,
    name: "James Anderson",
    joinedDate: "May 30, 2022",
    orderedItems: 6,
    status: "Active",
  },
  {
    id: 10123,
    name: "Emma Lee",
    joinedDate: "Aug 17, 2023",
    orderedItems: 2,
    status: "Active",
  },
];
