export const productsTableData = [
  {
    id: 1123,
    product: "Leather Phone Case",
    date: "Jun 29,2022",
    customerName: "Afaq Karim",
    status: "Deactive",
    amount: "$400.00",
  },
  {
    id: 1124,
    product: "Leather Laptop Bag",
    date: "Jul 15,2022",
    customerName: "Emily Jones",
    status: "Active",
    amount: "$899.00",
  },
  {
    id: 1125,
    product: "Leather Bag",
    date: "Aug 1,2022",
    customerName: "John Smith",
    status: "Deactive",
    amount: "$599.00",
  },
  {
    id: 1126,
    product: "Leather Phone Case",
    date: "Sep 10,2022",
    customerName: "Daniel Brown",
    status: "Deactive",
    amount: "$1299.99",
  },
  {
    id: 1127,
    product: "Leather Phone Case",
    date: "Oct 5,2022",
    customerName: "Sophia Rodriguez",
    status: "Active",
    amount: "$899.00",
  },
  {
    id: 1128,
    product: "Leather Phone Case",
    date: "Nov 20,2022",
    customerName: "Liam Johnson",
    status: "Deactive",
    amount: "$1199.00",
  },
  {
    id: 1129,
    product: "Leather Phone Case",
    date: "Dec 3,2022",
    customerName: "Isabella Martinez",
    status: "Deactive",
    amount: "$999.00",
  },
  {
    id: 1130,
    product: "Leather Phone Case",
    date: "Jan 15,2023",
    customerName: "Ethan Wilson",
    status: "Active",
    amount: "$499.00",
  },
  {
    id: 1131,
    product: "Leather Bag",
    date: "Feb 6,2023",
    customerName: "Emma Thompson",
    status: "Deactive",
    amount: "$699.00",
  },
  {
    id: 1132,
    product: "Leather Bag",
    date: "Mar 25,2023",
    customerName: "Noah Garcia",
    status: "Deactive",
    amount: "$799.00",
  },
  {
    id: 1133,
    product: "Leather Cap",
    date: "Apr 5,2023",
    customerName: "Olivia Clark",
    status: "Active",
    amount: "$99.00",
  },
];
